# Generated by Django 5.2.17 on 2026-09-03 13:57

from django.db import migrations
from django.contrib.auth.management import create_permissions
from django.apps import apps as global_apps

def create_store_manager_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    # Force creation of permissions for the store app just in case this is a fresh db
    # We use global_apps because create_permissions requires AppConfig
    store_config = global_apps.get_app_config('store')
    create_permissions(store_config, apps=global_apps, verbosity=0)
    
    group, created = Group.objects.get_or_create(name='Store Manager')
    
    models_to_manage = ['category', 'product', 'order', 'orderitem', 'review']
    
    permissions = Permission.objects.filter(
        content_type__app_label='store',
        content_type__model__in=models_to_manage
    )
    
    if permissions.exists():
        group.permissions.set(permissions)

def revert_store_manager_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Store Manager').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_users_wishlist'),
    ]

    operations = [
        migrations.RunPython(create_store_manager_group, revert_store_manager_group),
    ]
